appname = core_api
httpport = ${CORE_API_HTTP_PORT}
runmode = prod

parameterStore = ${PARAMETER_STORE}
PGuser = ${CORE_API_DB_USER}
PGpass = ${CORE_API_DB_PASS}
PGhost = ${CORE_API_DB_URL}
PGdb   = ${CORE_API_DB_NAME}
PGschema = ${CORE_API_DB_SCHEMA}
autorender = false
copyrequestbody = true
